[package]
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2018"
name = "relm4"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.14.0"
#fragile = "1.0"
crossbeam-channel = "0.5"
glib = "0.14.0"
glib-sys = "0.14.0"
gobject-sys = "^0.10.0"
gtk4 = "0.1.0"
libc = "^0.2.54"
log = "^0.4.6"
